sonar.projectKey=red-backend
sonar.projectName=Red Project Backend
sonar.projectVersion=1.0

sonar.sources=src
sonar.java.binaries=target/classes

sonar.exclusions=node_modules/**,dist/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://host.docker.internal:9000
sonar.token=sqp_99d8e1f329f141b3af67b2f534b3a254f98ed3cf
